### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by amandafanny** [neo4j-examples/langchain-starter-kit#5]
<img width="603" alt="image" src="https://github.com/user-attachments/assets/e209d69d-9026-484a-9795-819bd3ec797a" />

**Comment by amandafanny** [comment]
When I remove lock file,and run `poetry install`.I install the packages.

```
(poetry) (base) Ξ github/langchain-starter-kit git:(main) ▶ poetry run uvicorn app.server:app --reload --port=8000
INFO:     Will watch for changes in these directories: ['/Users/yuqing/ghj/code/github/langchain-starter-kit']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [72765] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yuqing/ghj/code/github/my-app/app/server.py", line 6, in <module>
    from langchain_anthropic import ChatAnthropic
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/langchain_anthropic/__init__.py", line 1, in <module>
    from langchain_anthropic.chat_models import ChatAnthropic, ChatAnthropicMessages
  File "/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/langchain_anthropic/chat_models.py", line 45, in <module>
    from langchain_core.messages.ai import InputTokenDetails, UsageMetadata
ImportError: cannot import name 'InputTokenDetails' from 'langchain_core.messages.ai' (/Users/yuqing/miniconda3/envs/poetry/lib/python3.11/site-packages/langchain_core/messages/ai.py)
```

**Comment by kinue00** [comment]
I have this:

`kinue@MeinM1air langchain-starter-kit % poetry install
Installing dependencies from lock file

Cannot overwrite a value (at line 6, column 18)`

when running `poetry install`.

**Comment by kinue00** [comment]
I have checked the poetry.lock file and I found that there are 2 lines indicating the same version of a package. I deleted the redundant lines (there are many, I just use a editor which can see line number and keep excuting `poetry install`), finally have a "good" lock file that I here attach (delete .txt to use).
[poetry.lock.txt](https://github.com/user-attachments/files/18313918/poetry.lock.txt)

Bad new is new error:
```
kinue@MeinM1air langchain-starter-kit % poetry install
Installing dependencies from lock file

Because langchain-starter-kit depends on fastapi (^0.111.0) which doesn't match any versions, version solving failed.
```

**Comment by kinue00** [comment]
> I have checked the poetry.lock file and I found that there are 2 lines indicating the same version of a package. I deleted the redundant lines (there are many, I just use a editor which can see line number and keep excuting `poetry install`), finally have a "good" lock file that I here attach (delete .txt to use). [poetry.lock.txt](https://github.com/user-attachments/files/18313918/poetry.lock.txt)
> 
> Bad new is new error:
> 
> ```
> kinue@MeinM1air langchain-starter-kit % poetry install
> Installing dependencies from lock file
> 
> Because langchain-starter-kit depends on fastapi (^0.111.0) which doesn't match any versions, version solving failed.
> ```

![Screenshot 2025-01-06 at 14 48 15](https://github.com/user-attachments/assets/9b4ffecd-65e7-41da-909d-db2f85c645fd)
I think the lock file is not updated....

**Comment by kinue00** [comment]
> > I have checked the poetry.lock file and I found that there are 2 lines indicating the same version of a package. I deleted the redundant lines (there are many, I just use a editor which can see line number and keep excuting `poetry install`), finally have a "good" lock file that I here attach (delete .txt to use). [poetry.lock.txt](https://github.com/user-attachments/files/18313918/poetry.lock.txt)
> > Bad new is new error:
> > ```
> > kinue@MeinM1air langchain-starter-kit % poetry install
> > Installing dependencies from lock file
> > 
> > Because langchain-starter-kit depends on fastapi (^0.111.0) which doesn't match any versions, version solving failed.
> > ```
> 
> ![Screenshot 2025-01-06 at 14 48 15](https://private-user-images.githubusercontent.com/44191239/400308092-9b4ffecd-65e7-41da-909d-db2f85c645fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDQyMTAsIm5iZiI6MTczNjE0MzkxMCwicGF0aCI6Ii80NDE5MTIzOS80MDAzMDgwOTItOWI0ZmZlY2QtNjVlNy00MWRhLTkwOWQtZGIyZjg1YzY0NWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA2MTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZTFhNjE3NmQxMmU0NDFmN2JjN2NlNzFhZmEyMDdkNDQ2ZTRjYWFjNTlkM2U3NDY1NDYzMmJlNmVhMWM1MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sf7Bbf4wLUvBAFm5NSiCsKeCZ12VKSmB8H8t8Avyk_E) I think the lock file is not updated....

I think I kinda solved the issue. The target is to use a newer version of fastapi.
- step 1: Install Rust and Cargo
```
# Install rustup first
brew install rustup-init
# Initialize rustup
rustup-init
# Add Rust to your PATH by running either:
source "$HOME/.cargo/env"
# OR for permanent addition to zsh:
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
# Verify installation
rustc --version
cargo --version
```

- step 2: Downgrade Python
```
poetry env use python3.12
```

- step 3: Finally
```
poetry install
```
